### ISSUE TITLE
scaleX and scaleY scale wrong axis when image is rotated at 90, -90, 270 or -270 angles

### ISSUE THREAD

**Issue by penafo** [fengyuanchen/cropper#633] opened 2016-03-13 02:24 UTC
You can test this on the demo at http://fengyuanchen.github.io/cropper/

I understand the logic ... scale X and scale Y always relate to the original position of the image, but if the user rotates it to a 90 degree (or -90, or 270 or -270) the axis are now different and the user expects his actions to be reflected on the new image, not the original one.

**Comment by afeibus** [comment] 2016-05-07 03:51
The issue is the css transform setting on the image.  The ordering for transform is _right-to-left_ in the way it is applied, so the `transform: rotate(-45deg) scale(-1,1)` does the scale first and then the rotate, which is backwards from what you probably wanted to do.

The fix is in cropper.js, swap lines 181-183 with lines 185-187 and see if that satisfies.

**Comment by fengyuanchen** [comment] 2016-05-10 13:13
@afeibus Awesome idea! It just works. Thank you very much!

**Closed** 2016-05-10 13:16 UTC
