### ISSUE TITLE
Zoom in without distorting the image

### ISSUE THREAD

**Issue by denar50** [fengyuanchen/cropper#693] opened 2016-05-19 10:51 UTC
Hello. Is there a way to zoom in without distorting the image? For example let's say I want to crop a huge image 2500 x 2000 using the browser on my phone (whose screen is 400 x 400). Currently the cropper allows me to zoom in as much as I want to, but I just want to zoom in enough without distorting the image. 
Is there a way to set a limit to the zoom in function for this case?

**Comment by RegisFrey** [comment] 2016-05-26 20:10
This is a duplicate of https://github.com/fengyuanchen/cropper/issues/279 see the last entry there for a partial solution.

Also https://github.com/fengyuanchen/cropper/issues/225 is a similar concern (note that strict was replaced by viewMode: 1 https://github.com/fengyuanchen/cropper/blob/master/CHANGELOG.md#200-nov-11-2015)

**Comment by fengyuanchen** [comment] 2016-05-30 11:41
@RegisFrey Thanks for reply this~

**Closed by fengyuanchen** 2016-05-30 11:41 UTC
