### ISSUE TITLE
Handling EXIF Image Orientation

### ISSUE THREAD

**Issue by bameyrick** [fengyuanchen/cropper#120] opened 2014-12-03 16:18 UTC
Firstly, thanks for the great plugin! However I've noticed a small issue; When loading an image in with EXIF orientation, everything works as expected until the "getDataURL" method is called. The generated image does not crop correctly and the rotation of the cropped image is incorrect.

Below I've provided screen shots of the chosen crop area and the image generated by "Get Data URL (JPG)". The image was taken on an iPad in portrait mode.

![img_0112](https://cloud.githubusercontent.com/assets/8447446/5283688/06485788-7b07-11e4-9e24-85dbad001080.PNG)

![img_0113](https://cloud.githubusercontent.com/assets/8447446/5283701/15712c3a-7b07-11e4-8ec3-78c30ec05684.PNG)

The white area in the generated image only seems to happen when a crop is taken near the bottom the image.

Thanks

**Comment by lucatros** [comment] 2015-02-08 20:34
Having the same issue. Anybody found a workaround for this issue?

**Comment by fengyuanchen** [comment] 2015-02-18 10:17
Maybe it is more easy to handle the EXIF Orientation on the server-side.

**Comment by jasonterando** [comment] 2015-02-24 15:32
First, thanks for an outstanding plug-in!!!  I poked around to see if there was a client-side library I could use to do the EXIF correctio.  There are a couple of JS EXIF readers (like https://github.com/jseidelin/exif-js), and I think I can use that info, load the image into a canvas, rotate the image in the canvas, and then get the data.  I'll play around with this more and post any luck I have.

In the meantime, for .NET land, I put together a c# static method (which I wired up to a WebAPI, but you can use it with WCF or whatever).  You'll need to add a project reference to System.Drawing (and add namespaces to your class for System.Drawing, System.Drawing.Imaging and System.Text).
```
        /// <summary>
        /// Removes EXIF rotation from an image
        /// </summary>
        /// <param name="URI"></param>
        /// <returns></returns>
        public static string RemoveEXIFRotation(string URI)
        {
            // Decode the URI information
            string base64Data = Regex.Match(URI, @"data:image/(?<type>.+?),(?<data>.+)").Groups["data"].Value;
            byte[] binData = Convert.FromBase64String(base64Data);
 
            using (var stream = new MemoryStream(binData))
            {
                Bitmap bmp = new Bitmap(stream);

                if(Array.IndexOf(bmp.PropertyIdList, 274) > -1)
                {
                    var orientation = (int) bmp.GetPropertyItem(274).Value[0];
                    switch(orientation)
                    {
                        case 1:
                            // No rotation required.
                            return URI;
                        case 2:
                            bmp.RotateFlip(RotateFlipType.RotateNoneFlipX);
                            break;
                        case 3:
                            bmp.RotateFlip(RotateFlipType.Rotate180FlipNone);
                            break;
                        case 4:
                            bmp.RotateFlip(RotateFlipType.Rotate180FlipX);
                            break;
                        case 5:
                            bmp.RotateFlip(RotateFlipType.Rotate90FlipX);
                            break;
                        case 6:
                            bmp.RotateFlip(RotateFlipType.Rotate90FlipNone);
                            break;
                        case 7:
                            bmp.RotateFlip(RotateFlipType.Rotate270FlipX);
                            break;
                        case 8:
                            bmp.RotateFlip(RotateFlipType.Rotate270FlipNone);
                            break;
                    }
                    // This EXIF data is now invalid and should be removed.
                    bmp.RemovePropertyItem(274);
                }

                ImageCodecInfo jgpEncoder = ImageCodecInfo.GetImageDecoders().First(x => x.FormatID == ImageFormat.Jpeg.Guid);

                // Create an Encoder object based on the GUID
                // for the Quality parameter category.
                System.Drawing.Imaging.Encoder myEncoder = System.Drawing.Imaging.Encoder.Quality;

                // Create an EncoderParameters object.
                // An EncoderParameters object has an array of EncoderParameter
                // objects. In this case, there is only one
                // EncoderParameter object in the array.
                EncoderParameters myEncoderParameters = new EncoderParameters(1);

                EncoderParameter myEncoderParameter = new EncoderParameter(myEncoder, 100L);
                myEncoderParameters.Param[0] = myEncoderParameter;

                using(MemoryStream output = new MemoryStream(binData.Length))
                {
                    bmp.Save(output, jgpEncoder, myEncoderParameters);
                    output.Position = 0;
                    int len = (int) output.Length;
                    byte[] results = new byte[len];
                    output.Read(results, 0, len);

                    return string.Format("data:image/jpg;base64,{0}", Convert.ToBase64String(results));
                }
            }
        }
```

**Comment by fengyuanchen** [comment] 2015-02-25 01:45
Thank you @jasonterando .

**Comment by landfill16** [comment] 2015-03-08 20:39
Thanks  @jasonterando .  I'm new to jQuery and html5 but I am also having trouble with exif orientation.  Could please provide an example of where you put the code to call your web service and processed the response ?

**Comment by jmagnusson** [comment] 2015-04-30 14:54
Did you guys look further into using [exif-js](https://github.com/jseidelin/exif-js)?

**Comment by bbrooks** [comment] 2015-07-10 23:55
If you're getting an image from the user, you can use https://github.com/blueimp/JavaScript-Load-Image to get it into the correct orientation before using cropper:

```js
        $('#yourFileInput').on('change', function(e) {
            e.preventDefault();
            e = e.originalEvent;
            var target = e.dataTransfer || e.target,
                file = target && target.files && target.files[0],
                options = {
                    canvas: true
                };

            if(!file) {
                return;
            }

            loadImage.parseMetaData(file, function(data) {
                
                // Get the correct orientation setting from the EXIF Data
                if (data.exif) {
                    options.orientation = data.exif.get('Orientation');
                }
                
                // Load the image from disk and inject it into the DOM with the correct orientation
                loadImage(
                    file,
                    function(canvas) {
                        var imgDataURL = canvas.toDataURL();
                        var $img = $('<img>').attr('src', imgDataURL);
                        $('body').append($img);

                        // Initiate cropper once the orientation-adjusted image is in the DOM
                        $img.cropper();
                    },
                    options
                );
            });
        });
```

**Comment by kingwrcy** [comment] 2015-07-16 00:55
@bbrooks nice work,you saved my day,awesome plugin.

**Comment by dekortage** [comment] 2015-08-28 16:11
I encountered the same problem with iOS devices while I was adapting the Crop Avatar example to my own purposes, but I solved it on the PHP side.  In cropper.php, in the setFile function, starting at line 54, there is this block:

    if ($result) {
        $this -> src = $src;
        $this -> type = $type;
        $this -> extension = $extension;
        $this -> setDst();
    } else {
        $this -> msg = 'Failed to save file';
    }

To this, I incorporated a solution to this problem [as described on StackExchange by user462990](http://stackoverflow.com/questions/7489742/php-read-exif-data-and-adjust-orientation/21797668#21797668).  So that whole block now reads:

    if ($result) {
    
    	$exif = exif_read_data($src);
    	if (!empty($exif['Orientation'])) {
    		$imageToRotate = imagecreatefromjpeg($src);
    		switch ($exif['Orientation']) {
    
    			case 3:
    				$imageToRotate = imagerotate($imageToRotate, 180, 0);
    				break;
    
    			case 6:
    				$imageToRotate = imagerotate($imageToRotate, -90, 0);
    				break;
    
    			case 8:
    				$imageToRotate = imagerotate($imageToRotate, 90, 0);
    				break;
    				
    		}
    		imagejpeg($imageToRotate, $src, 90);
    	}
    
    	$this -> src = $src;
    	$this -> type = $type;
    	$this -> extension = $extension;
    	$this -> setDst();
    	
    } else {
    	 $this -> msg = 'Failed to save file';
    }

This works for me.

**Comment by fengyuanchen** [comment] 2015-08-29 03:17
@dekortage If the user rotate the image with cropper on browser side, and you rotate it again on server side, then what will happen?

**Comment by edbond** [comment] 2015-08-29 05:59
I am using [exif-js](https://github.com/exif-js/exif-js) to determine orientation and rotate initially in browser. Server uses data from cropper. Here is my code. Note that there any 1-8 orientations in exif.

```coffee
      EXIF.getData img.get(0), () ->
        orientation = EXIF.getTag(this, "Orientation")
        # console.log "orientation", orientation

        img.cropper
          strict: false
          aspectRatio: 1.47
          crop: (e) ->
            $("#photo_offset").val(JSON.stringify(e))

        # rotate according to orientation
        switch orientation
          when 2
            img.cropper('scale', -1, 1) # Flip horizontal
          when 3
            img.cropper('scale', -1)
          when 4
            img.cropper('scale', 1, -1)
          when 5
            img.cropper('scale', -1, 1)
            img.cropper('rotate', -90)
          when 6
            img.cropper('rotate', 90)
          when 7
            img.cropper('scale', 1, -1)
            img.cropper('rotate', -90)
          when 8
            img.cropper('rotate', -90)

        $(".rotate-left").off("click")
        $(".rotate-left").on "click", (e) ->
          e.preventDefault()
          e.stopPropagation()
          img.cropper('rotate', 90)
```

On server I'm using ruby-on-rails and carrierwave to handle uploads. Code uses Rmagick. Here is code. It extracts x,y,w,h,rotate,scale values that cropper sends to server. `strip!` removes exif info.

```ruby
    manipulate! do |img|
      Rails.logger.debug "[PHOTO] offset: #{model.photo_offset.pretty_inspect}".yellow
      x, y, w, h, rotate, scaleX, scaleY = model.photo_offset.values_at("x", "y",
        "width", "height", "rotate", "scaleX", "scaleY").map { |v| v.to_f.round(2) }

      crop = "#{w}x#{h}!+#{x}+#{y}"
      Rails.logger.debug "[PHOTO] crop: #{crop.inspect}".green

      # img.auto_orient!
      img.flip! if scaleY == -1
      img.flop! if scaleX == -1
      img.rotate!(rotate) if rotate.present? && !rotate.zero?
      img.crop!(x,y,w,h)
      img.strip!

      img = yield(img) if block_given?
      img
    end
```

Blog post about exif rotations: http://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/
and there is link to example images which may be used to test:
https://github.com/recurser/exif-orientation-examples

I don't have any problems with this example images, however MacOs guys complains so the code is not 100% complete.

HTH

**Comment by dekortage** [comment] 2015-08-29 13:44
@fengyuanchen -- it seems to work fine in my limited testing.  The client side previews fine, and the transformations are sent up to the server as if the image is oriented correctly.  It's just that the server uploads the image at a 90° angle before applying the cropping/transformations.  The server just needs to reorient the file back to what the user saw client-side, before applying the server-side transformations/cropping.

However, I would definitely welcome more extensive inquiry/experimentation into this.

**Comment by MarcusJT** [comment] 2015-10-07 12:49
If the problem is that sometimes the image rendered to a canvas is correctly orientated and sometimes it isn't, then given an image with width X and height Y then can't we determine which is longest and store that as L then render the image to a canvas of size LxL, then check pixels X,L and Y,L to see which way round the image has been rendered, then rotate and crop the area as required, giving us the correct outcome in all cases?

**Comment by fengyuanchen** [comment] 2015-10-07 16:19
@MarcusJT What about a square image?

**Comment by MarcusJT** [comment] 2015-10-07 16:25
Ha! Good point... damn...

**Comment by rern** [comment] 2015-11-17 15:12
1. Get exif orientation with [exif-js](https://github.com/exif-js/exif-js)
2. new FileReader for new Image
3. Create canvas
4. context.transform and context.drawImage
5. Get rotated image from canvas

```javascript
$('#file').change(function () {
	var file = this.files[0];
	
	EXIF.getData(file, function () { // 1. exif-js
		var ex = EXIF.getTag(file, 'Orientation');
		var ori = ex ? ex : 1; // set undefined to 1
		reader(file, ori);
	});
});

function reader(file, ori) {
	var reader = new FileReader(); // 2. FileReader
	
	reader.onload = function (e) {
		var img = new Image();
		img.onload = function () {
			if (ori === 1 || ori === 3) {
				var w = this.width;
				var h = this.height;
			} else {
				var h = this.width;
				var w = this.height;
			}
			
			if (ori === 1) {
				var img0 = img; // normal image
			} else {
				var canvas = document.createElement('canvas'); // 3. canvas
				var ctx = canvas.getContext('2d');
				
				if (ori === 3) { // 4. transform, drawImage
					ctx.transform(-1, 0, 0, -1, w, h);
					ctx.drawImage(img, 0, 0, w, h);
				} else if (ori === 6) {
					ctx.transform(0, 1, -1, 0, w, 0);
					ctx.drawImage(img, 0, 0, h, w);
				} else {
					ctx.transform(0, -1, 1, 0, 0, h);
					ctx.drawImage(img, 0, 0, h, w);
				}
				
				var img0 = canvas.toDataURL(); // 5. get image
			}
			
			$('body').append('<img id="image">');
			$('#image').prop('src', img0).one('load', function () {
				$(this).cropper();
			});
		}
		img.src = e.target.result;
	}
	reader.readAsDataURL(file);
}
```

**Comment by 50bbx** [comment] 2015-11-18 01:08
@rern really great thanks! I used your solution about an hour ago. What I discovered is that in iOS (Chrome and Safari) the orientation is correct, without any workaround but if you try on Chrome desktop with a photo taken with an iPhone (with exif) it will generate the issue. This is is a per-browser issue. I will add more details as soon as I can.

**Comment by fengyuanchen** [comment] 2015-11-18 03:24
You can try the [Loader](https://github.com/fengyuanchen/loader) to translate Exif Orientation by canvas and get a pure image for Cropper.

**Comment by rern** [comment] 2015-11-18 12:57
@50bbx - I've tried Chrome on Windows 10. iPhone photos display correctly.
(IE < 10 not support dataView, the solution will not do the trick there.)
BTW I've updated the code, switch out exif-js for a handy function from stackoverflow. May be It's small enough for @fengyuanchen to consider including it in his wonderful code.

**Comment by 50bbx** [comment] 2015-11-18 14:36
@rern Sorry, you are right, I was using half of your solution and half of edbond. I see the image correctly rotated now. The problem is I only see a very small piece. This is the result:
![cropper with exif](https://cloud.githubusercontent.com/assets/3308680/11243596/31d55714-8e09-11e5-9d0d-b55800ee932e.jpg)
as you can see it is just the upper left corner of the image. I think the base64 conversion from the canvas doesn't work correctly. I also inspected the element with chrome and the image is not hidden fullsize in the cropper: it appears the image has been cropped by the rotation process in the reader function. I didn't change anything, except from where I append the image.

**Comment by 50bbx** [comment] 2015-11-18 14:39
@fengyuanchen I've tried, I've used precisely @bbrooks solution but it was so slow I had to revert my changes. I'm sorry I cannot provide that code anymore. But I simply copied and pasted that solution in my code (that is pretty straight forward and doesn't do anything complex nor strange)

**Comment by rern** [comment] 2015-11-19 04:16
@50bbx - You're right. My bad. There're some flaw in the code. It's been corrected.

**Comment by fengyuanchen** [comment] 2015-12-06 07:47
As of v2.2.0, the Cropper will read the Exif Orientation information and override it to its default value: `1`. This may fix this problem.

**Comment by kaynz** [comment] 2016-01-14 08:40
Not fixed on 2.2.4 =(

**Comment by fengyuanchen** [comment] 2016-01-14 09:18
@kaynz If your browser supports [Typed Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray) (iOS Safari 8.4+), then this issue may be fixed since  Cropper [v2.2.0](https://github.com/fengyuanchen/cropper/releases/tag/v2.2.0).

> Reference: http://caniuse.com/TypedArrays

**Comment by kaynz** [comment] 2016-01-14 09:27
@fengyuanchen thanks for the quick answer. I am using iOS Safari 9, which supports Typed Array.

**Comment by fengyuanchen** [comment] 2016-01-14 09:38
@kaynz Then I don't know why. Sorry!

**Comment by kaynz** [comment] 2016-01-14 10:47
@fengyuanchen I just set checkOrientation to false and now it is working on iOS Safari. Any ideas?

**Comment by fengyuanchen** [comment] 2016-01-15 02:41
@kaynz Are you using the latest version (v2.2.4)?

**Comment by kaynz** [comment] 2016-01-15 07:15
@fengyuanchen yes.

**Comment by fengyuanchen** [comment] 2016-01-15 11:08
@kaynz Do you catch any error in the console?.

**Comment by mjvestal** [comment] 2016-01-20 18:01
I also set checkOrientation to false, and it fixes the issue on iOS Safari, but broke on desktop browsers.  See my comment here: https://github.com/fengyuanchen/cropper/issues/509#issuecomment-172633656

**Comment by every2ndcountsxc** [comment] 2016-02-01 21:55
@mjvestal I followed your suggested changes by commenting out those lines, and I also set checkOrientation to false in my options, but I'm still having issues. Basically, when I choose to take a photo from my camera, on FIRST file load the width is distorted. When I then choose to take different photo, there the new photo that loads isn't distorted.

**Comment by fengyuanchen** [comment] 2016-02-02 06:00
@every2ndcountsxc You can build the dist files from master branch on your computer and try it again:
```
git clone https://github.com/fengyuanchen/cropper.git
cd cropper
npm install
gulp release
```

**Comment by every2ndcountsxc** [comment] 2016-02-02 14:29
Thanks @fengyuanchen but I don't believe "trying again" is a helpful solution. 

I do, however, think my issue is something separate from the main issue(s) in this thread. 

Using [_your own demo_](http://fengyuanchen.github.io/photo-editor/) on my iPhone 6 (iOS9), I imported a file by taking a photo with the camera. This is the result:

![img_1823](https://cloud.githubusercontent.com/assets/4258232/12752148/ff0e2b1e-c98e-11e5-9850-5c741b7fe251.PNG)

As you can see, the image is distorted, as if the file reader was expecting a landscape image. 

When I originally thought my problem was just a matter of me not implementing the plugin correctly, I'm now realizing that there is something going on with the way the mobile device is interpreting the image from the camera. 

Thoughts on how to solve this? Thanks!

**Comment by mjvestal** [comment] 2016-02-02 17:33
@every2ndcountsxc, the thing that works for me is NOT setting checkOrientation to false + commenting out those lines

**Comment by every2ndcountsxc** [comment] 2016-02-02 19:03
@mjvestal thank you. That was the kind of solution I was looking for. Works like a charm. Cheers!

**Comment by Win10Developer** [comment] 2016-02-03 19:14
In the first image on this post, there is a button 'Get data URL' which I assume puts the dataurl string into the text box also shown in the image. I'm looking for sample code to get this as I haven't been able to acquire the canvas dataurl string in javascript (my javascript knowledge is lacking a a little, I'm a dot net developer)
Can anybody provide the snippet of javascript that creates dataurl?

**Comment by yelhouti** [comment] 2016-02-16 06:41
@fengyuanchen I think @mjvestal is right, may be you should remove the 2 lines he mentioned from the code (if statement after //modern browsers). by the way thank you @mjvestal.

**Comment by yelhouti** [comment] 2016-02-16 06:46
@Win10Developer I shouldn't be answering here since it's not the best place to ask, but here it is:
```
$('#imgid').cropper({
    //your other options
    crop: function(e) {
         $('"textid").val($('#imgid').cropper('getCroppedCanvas').toDataURL("image/jpeg"));
   }				            
});
```

**Comment by IMM0rtalis** [comment] 2016-02-17 16:10
@fengyuanchen 

with "checkOrientation: false" i have the same problem like @every2ndcountsxc
the image i rotated but now it's quiet compressed.

with "checkOrientation: true" and version 2.2.5 the image is still not in the right direction.. :/

+1 for fixing this...

PS.: really nice plugin  :+1:

**Comment by IMM0rtalis** [comment] 2016-02-17 17:05
@fengyuanchen 

i built the latest version like you described, the image is now rotated like it should, but my wrapper has now at the top and at the button space (see image)
The space would be because the browser did not rotate the image in the img-tag (but took its width+height from there)... any ideas?

![12722538_10208887672926590_1336080580_o](https://cloud.githubusercontent.com/assets/1506919/13117576/d4c0a814-d5a0-11e5-946e-0438e39689ab.jpg)

**Comment by fengyuanchen** [comment] 2016-02-18 10:20
Hi, everyone, please provide your iOS and Safari version here once you need to comment here.

**Comment by IMM0rtalis** [comment] 2016-02-18 11:05
iOS 9.2.1 on iPhone 5S

**Comment by zilions** [comment] 2016-03-01 10:55
I'm using iOS 9.2 on an iPhone 62. All images that I add to the cropper via selecting the "Take Photo" option are rotated incorrectly. Although, if the image is added via an already existing image, using the "Photo Library" option, the image is the correct rotation.

Here is are screenshots of me using the "Take Photo" option:

![img_2164](https://cloud.githubusercontent.com/assets/6722591/13424996/cc426a84-dfef-11e5-9fd0-eb9cea3aa5da.jpg)
![img_2165](https://cloud.githubusercontent.com/assets/6722591/13424997/cc459ff6-dfef-11e5-8102-ac9b6e991739.jpg)

**Comment by samrayner** [comment] 2016-03-17 16:43
Can confirm that the following fixed iPhone uploads rotating for me:

```
rotatable: true
checkOrientation: true
```

And commenting out
https://github.com/fengyuanchen/cropper/blob/master/src/js/utilities.js#L53-L55

**Comment by zilions** [comment] 2016-03-21 09:04
Can also confirm that the fix from @samrayner works well on Safari. Thanks for sharing.

**Comment by zilions** [comment] 2016-04-08 07:40
@samrayner's solution only seems to work some of the time. I believe it does not work for images that were taken as landscape. Unfortunately, there are still many issues with the cropper and image orientation.

**Comment by zilions** [comment] 2016-04-21 01:08
@fengyuanchen - Any progress on this?

**Comment by zilions** [comment] 2016-04-21 01:49
After weeks of debugging, I have found that @bbrooks solution with the `Javascript-Load-Image` plugin is the best solution. It may be slightly slower (since it is converting to base64 along with reading meta data), yet it is basically bulletproof. Have tested it in many versions of iOS, Chrome and Firefox, and all the images that used to be rotated incorrectly, wrong aspect ratio and image squished now work perfectly as expected. Thanks @bbrooks!

**Comment by luck2011** [comment] 2016-05-09 16:55
@bbrooks why I use requireJS to load this 'JavaScript-Load-Image' all.min.js, I can't get ```loadImage.parseMetaData``` method from the callback function. When I use a html script tag to load it, then ```loadImage``` will have such method ```loadImage.parseMetaData```?

**Comment by ghybs** [comment] 2016-05-29 04:28
Hi,

I am also facing this problem.
I experienced the exact same symptoms as many other issues on the repo (90deg left-rotated image, inverted height-width aspect ratio / distortion, depending on options, external workaround tried, etc.)

In my case I develop an hybrid (Cordova-based) iOS app, so I use this plugin within a UIWebView (not Safari).

Therefore the `IS_SAFARI` browser sniffing test was not catching up the WebView behaving like on Safari.
Adding an extra platform sniffing test (to detect iPhone / iPad / iPod) and OR'ing it with `IS_SAFARI` solved the issue for me.

**Comment by yelhouti** [comment] 2016-05-29 06:38
Hi @ghybs can you say how you did the test for the other things? I have the same problem

**Comment by kaynz** [comment] 2016-05-29 08:40
@ghybs Could you create a pull request?

**Comment by ghybs** [comment] 2016-05-29 14:11
Hi,

As for detecting the UIWebView, for now I just detect an iOS device:
http://stackoverflow.com/questions/4460205/detect-ipad-iphone-webview-via-javascript

This is not bullet proof in the case of a Web App, as I guess people could still use another browser on an iOS device.
Hopefully this already covers most cases.

I will try to make a PR when I have time.

**Comment by 1fabiopereira** [comment] 2016-12-01 17:51
I was having this problem, I did what @samrayner  suggested and worked perfectly.

**Comment by hengsoheak** [comment] 2016-12-07 08:33
I've mete this problem 

http://stackoverflow.com/questions/41002081/fengyuanchen-cropper-typeerror-url-createobjecturl-is-not-a-function

**Comment by GoToBoy** [comment] 2017-01-16 06:51
fixed this using  @bbrooks thanks

**Closed** 2017-07-29 05:17 UTC

**Comment by faradoxuz** [comment] 2019-04-17 12:08
> var img0 = canvas.toDataURL(); // 5. get image
@rern  add mime type like 
`canvas.toDataURL('image/jpeg');`
in ortder not to have big size
