### ISSUE TITLE
Since version 3.1 getCroppedCanvas doesn't resize the image

### ISSUE THREAD

**Issue by Samuel91** [fengyuanchen/cropper#970] opened 2018-02-15 18:37 UTC
I noticed now that since version 3.1 the cropper doesn't resize the image to the desired width. This is my code that worked perfectly with previous versions.

```
uploadSubmit.click(function() {

            croppedImg.cropper('getCroppedCanvas',{
                width: 600,
                fillColor: '#fff'
            }).toBlob(function (blob) {
                var formData = new FormData();

                formData.append('croppedImage', blob);
                formData.append('type', uploadPhpType);

                $.ajax('media-upload.php', {
                    method: "POST",
                    data: formData,
                    processData: false,
                    contentType: false,
                    dataType: "json", //the return type data is jsonn
                    success: function ( data ) {
                        [....]
                    },
                    error: function () {                     
                            [....]
                    }
                });
            }, 'image/jpeg', 0.80);
        });
```

**Comment by fengyuanchen** [comment] 2018-02-22 11:52
Any demo or screenshots?

**Comment by Samuel91** [comment] 2018-02-22 12:16
It's for me difficult to provide you a demo because I integrated it in a CMS in italian language.
There are no errors in the console and image is correctly cropped but the size remains the same as the uploaded image.

Would be happy to provide you additional info if you need.

**Comment by Samuel91** [comment] 2018-02-22 13:01
Pehaps I have understood: using getCroppedCanvas you have to specify width and hight values. With older versions width value was sufficient. So returning to my code, this works:

```
croppedImg.cropper('getCroppedCanvas',{
                width: 600,
                height: 600 / 1.6,
                fillColor: '#fff'
            }).toBlob {[...]}, 
'image/jpeg', 0.80);
        });
```

**Comment by fengyuanchen** [comment] 2018-03-03 04:44
Cannot reproduce. Please try on the latest version again.

**Comment by Samuel91** [comment] 2018-03-05 10:06
Problem still remains, previously it was possible to use getCroppedCanvas without specifing the image height (just width) and now without the height property the file remains with the original resolution.

**Comment by Samuel91** [comment] 2018-03-05 11:42
Original image
![linas-bam-518045-unsplash](https://user-images.githubusercontent.com/11197191/36973003-9392045a-2071-11e8-9708-20d049ed538a.jpg)

Uploaded image (imageSmoothingQuality=low)
![offerta-1 1](https://user-images.githubusercontent.com/11197191/36972975-73e00742-2071-11e8-9c39-9dacecf9ae2a.jpg)

Uploaded image (imageSmoothingQuality=medium)
![offerta-2](https://user-images.githubusercontent.com/11197191/36973033-ac4927c6-2071-11e8-9a02-880d7fd6128e.jpg)

**Comment by fengyuanchen** [comment] 2018-03-05 12:55
If you cannot provide a minimal example for reproduce, I will close this soon.

**Closed** 2018-03-11 04:53 UTC
