### ISSUE TITLE
Image container strange behaviour

### ISSUE THREAD

**Issue by adammo14** [fengyuanchen/cropper#1056] opened 2019-09-11 14:23 UTC
Hello,

(1)
I'm experiencing an issue where uploaded image doesn't fit the image container and is roughly a third of its width. This is random as I could upload the same photo again and it would be fine. The only CSS I've overwritten for the cropper was `#upload-image-container`. I have set a `max-height` and `min-width` but that shouldn't matter as I've tested without it and I was getting the same result. Please see attached screenshots.

(2)
I'd like my cropper-crop-box to be bigger (while retaining its aspect ratio) and I'm not sure how to do it. Could you please advise?

**Screenshots**
(1)
![image](https://user-images.githubusercontent.com/15087423/64704369-172d1180-d4a6-11e9-8480-5a8316810a48.png)

![image](https://user-images.githubusercontent.com/15087423/64704444-39269400-d4a6-11e9-8e41-3aace9ebc4ba.png)

(2)
![image](https://user-images.githubusercontent.com/15087423/64704918-f618f080-d4a6-11e9-8b27-b4fa7ca1e362.png)

**Additional context**
cropper options
```
$scope.$cropper = new Cropper($scope.cropperElement, {
    aspectRatio: $scope.aspectRatio,
    dragMode: 'move',
    cropBoxMovable: false,
    cropBoxResizable: false,
    zoomOnTouch: false,
    zoomOnWheel: false,
    toggleDragModeOnDblclick: false,
    strict: true,
    disabled: true
});
```

**Comment by fengyuanchen** [comment] 2019-09-14 05:01
Duplicate of a ton of issues.

**Comment by fengyuanchen** [comment] 2019-09-14 05:02
```css
img {
  width: 100%;
}
```

**Comment by fengyuanchen** [comment] 2019-09-14 05:03
Don't initialize the cropper before you see the image place in the right position.

**Closed by fengyuanchen** 2019-09-14 05:03 UTC
